ALTER TABLE trips ADD COLUMN IF NOT EXISTS additional_info TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS eta TIMESTAMPTZ;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS make TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS model TEXT;
